.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Pierre Vignet <pierre.vignet.contact@caramail.fr>,
.\"
.TH LIBGATBCORE 3 "July 10, 2017"
.\" Please adjust this date whenever revising the manpage.
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
libgatbcore \- library to develop new NGS data analysis softwares.

.SH DESCRIPTION
GATB-Core natively provides the following high-performance and memory-efficient operations
.br
Reads handling:
.br
    FASTA/FASTQ parsing and writing (plain text and gzipped files are supported)
    Parallel iteration of sequences
.br
K-mer:
    K-mer counting
    Minimizer computation of k-mers, partitioning of datasets by minimizers
    Bloom data structure of k-mers
    Hash table of k-mers
    Minimal perfect hash function of k-mers
    Arbitrarily large k-mers representations
.br
de Bruijn graph:
    graph construction
    graph traversal operations (contigs, unitigs)
    graph simplifications for assembly (tip removal, bulge removal)
.br
Other optimized data structures
In addition to the de Bruijn graph data structure, GATB-Core provides several other ones that can be of interest for general purpose developments.
.br
These are:
    Open-Addressing Hash Table
    Linked-List Hash Table
    Bloom Filters. There are several flavors: basic, cache-optimized, optimized for k-mer neighbors; accessible through BloomFactory.
    Minimal Perfect Hash Function (BBHash)

.SH "SEE ALSO"
.BR libgatbcore (1)
.br
The programs are documented fully by the Genscale Team
available at https://github.com/GATB/gatb-core/wiki

.SH AUTHORS
This manual page was written by Pierre Vignet <pierre.vignet.contact@caramail.fr>
for the Debian project (and may be used by others).